export const API_ERRORS = {
  MISSING_API_KEY: { code: 'MISSING_API_KEY', message: 'API key is required. Include it in the Authorization header as "Bearer nxai_..."', status: 401 },
  INVALID_API_KEY: { code: 'INVALID_API_KEY', message: 'The API key provided is invalid.', status: 401 },
  API_KEY_REVOKED: { code: 'API_KEY_REVOKED', message: 'This API key has been revoked.', status: 401 },
  ACCOUNT_SUSPENDED: { code: 'ACCOUNT_SUSPENDED', message: 'Your account has been suspended. Contact support.', status: 403 },
  RATE_LIMIT_EXCEEDED: { code: 'RATE_LIMIT_EXCEEDED', message: 'Too many requests. Slow down and retry.', status: 429 },
  MONTHLY_QUOTA_EXCEEDED: { code: 'MONTHLY_QUOTA_EXCEEDED', message: 'Monthly API call quota exceeded. Upgrade your plan or wait for reset.', status: 429 },
  INVALID_REQUEST_BODY: { code: 'INVALID_REQUEST_BODY', message: 'The request body is invalid or malformed.', status: 400 },
  MISSING_REQUIRED_FIELD: { code: 'MISSING_REQUIRED_FIELD', message: 'Required field is missing.', status: 400 },
  INVALID_MODEL: { code: 'INVALID_MODEL', message: 'The specified model is not available. Check available models with GET /v1/models.', status: 400 },
  MODEL_NOT_AVAILABLE_ON_PLAN: { code: 'MODEL_NOT_AVAILABLE_ON_PLAN', message: 'The requested model is not available on your current plan. Upgrade to access premium models.', status: 403 },
  AI_SERVICE_UNAVAILABLE: { code: 'AI_SERVICE_UNAVAILABLE', message: 'The AI service is temporarily unavailable. Please retry.', status: 503 },
  AI_GENERATION_FAILED: { code: 'AI_GENERATION_FAILED', message: 'AI chat completion failed. Please try again.', status: 500 },
  AI_MODEL_NOT_AVAILABLE: { code: 'AI_MODEL_NOT_AVAILABLE', message: 'The requested AI model is not available on your plan.', status: 403 },
  INVALID_MESSAGES_FORMAT: { code: 'INVALID_MESSAGES_FORMAT', message: 'The messages array must contain at least one message with a valid role (system, user, assistant).', status: 400 },
  CONTEXT_LENGTH_EXCEEDED: { code: 'CONTEXT_LENGTH_EXCEEDED', message: 'The combined message length exceeds the model context window. Reduce the number of messages or switch to a model with a larger context window.', status: 400 },
  WEBHOOK_NOT_FOUND: { code: 'WEBHOOK_NOT_FOUND', message: 'Webhook not found.', status: 404 },
  WEBHOOK_DELIVERY_FAILED: { code: 'WEBHOOK_DELIVERY_FAILED', message: 'Failed to deliver webhook. The endpoint returned an error.', status: 200 },
  INVALID_WEBHOOK_URL: { code: 'INVALID_WEBHOOK_URL', message: 'The webhook URL is invalid.', status: 400 },
  WEBHOOK_LIMIT_EXCEEDED: { code: 'WEBHOOK_LIMIT_EXCEEDED', message: 'You have reached the maximum number of webhooks for your plan.', status: 400 },
}
