export const API_ERRORS = {
  MISSING_API_KEY: { code: 'MISSING_API_KEY', message: 'API key is required. Include it in the Authorization header as "Bearer ei_sk_..."', status: 401 },
  INVALID_API_KEY: { code: 'INVALID_API_KEY', message: 'The API key provided is invalid.', status: 401 },
  API_KEY_REVOKED: { code: 'API_KEY_REVOKED', message: 'This API key has been revoked.', status: 401 },
  ACCOUNT_SUSPENDED: { code: 'ACCOUNT_SUSPENDED', message: 'Your account has been suspended. Contact support.', status: 403 },
  RATE_LIMIT_EXCEEDED: { code: 'RATE_LIMIT_EXCEEDED', message: 'Too many requests. Slow down and retry.', status: 429 },
  MONTHLY_QUOTA_EXCEEDED: { code: 'MONTHLY_QUOTA_EXCEEDED', message: 'Monthly API call quota exceeded. Upgrade your plan or wait for reset.', status: 429 },
  INVALID_REQUEST_BODY: { code: 'INVALID_REQUEST_BODY', message: 'The request body is invalid or malformed.', status: 400 },
  MISSING_REQUIRED_FIELD: { code: 'MISSING_REQUIRED_FIELD', message: 'Required field is missing.', status: 400 },
  INVALID_CONTENT_TYPE: { code: 'INVALID_CONTENT_TYPE', message: 'Invalid content_type. Must be one of: property_description, social_post, whatsapp_msg, email_campaign, ad_copy, custom', status: 400 },
  INVALID_PROPERTY_TYPE: { code: 'INVALID_PROPERTY_TYPE', message: 'Invalid property_type.', status: 400 },
  GENERATION_LIMIT_EXCEEDED: { code: 'GENERATION_LIMIT_EXCEEDED', message: 'Count exceeds maximum of 10 per request.', status: 400 },
  AI_SERVICE_UNAVAILABLE: { code: 'AI_SERVICE_UNAVAILABLE', message: 'The AI service is temporarily unavailable. Please retry.', status: 503 },
  AI_GENERATION_FAILED: { code: 'AI_GENERATION_FAILED', message: 'AI content generation failed. Please try again.', status: 500 },
  AI_MODEL_NOT_AVAILABLE: { code: 'AI_MODEL_NOT_AVAILABLE', message: 'The requested AI model is not available on your plan.', status: 403 },
  PROPERTY_NOT_FOUND: { code: 'PROPERTY_NOT_FOUND', message: 'Property not found.', status: 404 },
  LEAD_NOT_FOUND: { code: 'LEAD_NOT_FOUND', message: 'Lead not found.', status: 404 },
  CONTENT_NOT_FOUND: { code: 'CONTENT_NOT_FOUND', message: 'Content not found.', status: 404 },
  WEBHOOK_NOT_FOUND: { code: 'WEBHOOK_NOT_FOUND', message: 'Webhook not found.', status: 404 },
  WEBHOOK_DELIVERY_FAILED: { code: 'WEBHOOK_DELIVERY_FAILED', message: 'Failed to deliver webhook. The endpoint returned an error.', status: 200 },
  INVALID_WEBHOOK_URL: { code: 'INVALID_WEBHOOK_URL', message: 'The webhook URL is invalid.', status: 400 },
  WEBHOOK_LIMIT_EXCEEDED: { code: 'WEBHOOK_LIMIT_EXCEEDED', message: 'You have reached the maximum number of webhooks for your plan.', status: 400 },
}
