import { withApiAuth } from '@/lib/api-auth'
import { apiSuccess } from '@/lib/api-response'
import { db } from '@/lib/db'

export const GET = withApiAuth(async (request, context) => {
  const developerId = context.developer.id as string
  const creditsRemaining = (context.developer.monthlyCallsLimit as number) - (context.developer.monthlyCallsUsed as number)

  // Content generated by type
  const contentByType = await db.generatedContent.groupBy({
    by: ['contentType'],
    where: { developerId },
    _count: { contentType: true },
    _avg: { tokensUsed: true },
  })

  // Most popular languages
  const contentByLanguage = await db.generatedContent.groupBy({
    by: ['language'],
    where: { developerId },
    _count: { language: true },
    orderBy: { _count: { language: 'desc' } },
  })

  // Most popular tones
  const contentByTone = await db.generatedContent.groupBy({
    by: ['tone'],
    where: { developerId, tone: { not: null } },
    _count: { tone: true },
    orderBy: { _count: { tone: 'desc' } },
  })

  return apiSuccess({
    by_type: contentByType.map(item => ({
      content_type: item.contentType,
      count: item._count.contentType,
      avg_tokens_used: item._avg.tokensUsed ? Math.round(item._avg.tokensUsed) : 0,
    })),
    by_language: contentByLanguage.map(item => ({
      language: item.language,
      count: item._count.language,
    })),
    by_tone: contentByTone.map(item => ({
      tone: item.tone,
      count: item._count.tone,
    })),
  }, { creditsRemaining })
})
